object CommonBuild {
    const val FUNCTION_MODULE = "function-module-di.gradle"
    const val TESTING_MODULE = "testing-module-di.gradle"
    const val UI_TESTING_MODULE = "ui-testing-module-di.gradle"
    const val FIREBASE_MODULE = "firebase-module-di.gradle"
    const val DATA_MODULE = "data-module-di.gradle"
    const val UI_MODULE = "ui-module-di.gradle"
    const val NavigationModule = "navigation-module-di.gradle"
    const val FeatureModule = "feature-module-di.gradle"
    const val COMPOSE_MODULE = "compose-module-di.gradle"
    const val KOIN_MODULE = "koin-module-di.gradle"
    const val KTOR_MODULE = "ktor-module-di.gradle"
    const val HiltDependencies = "hilt-module-di.gradle"
    const val LibraryDependencies = "library-module-di.gradle"
}