object Feature {
    const val USER_TICKETS = ":features:user-tickets"
    const val CONTACT_US = ":features:contact-us"
    const val ABOUT_US = ":features:about-us"
    const val TERMS_AND_CONDITIONS = ":features:terms-conditions"
    const val BOOKING_PAYMENT = ":features:booking-payment"
    const val ADD_PAYMENT = ":features:add-payment"
    const val SPLASH = ":features:splash"
    const val LOGIN = ":features:login"
    const val COMPLAINT = ":features:complaint"
    const val DRIVER_REVIEW = ":features:driver-review"
    const val USER_FORM = ":features:user-data"
    const val SET_PASSWORD = ":features:set-password"
    const val TICKET = ":features:ticket"
    const val SUGGESTION = ":features:suggestions"
    const val SIGN_UP = ":features:signup"
    const val RESET_PASSWORD = ":features:reset-password"
    const val PROFILE = ":features:profile"
    const val BOOKING = ":features:booking"
    const val PROFILE_SETTINGS = ":features:profile-settings"
    const val ROUTE = ":features:route"
    const val LINE_MAP = ":features:line-map"
    const val PRIVACY_POLICY = ":features:privacy-policy"
    const val RECHARGING = ":features:charging"
    const val HOME = ":features:home-screen"
    const val MAP = ":features:map"
    const val SCAN_QR = ":features:scan-qr"
    const val SEND_OTP = ":features:send-otp"
    const val APP_SETTINGS = ":features:app-settings"
    const val SELECT_SERVICE = ":features:select-service"
    const val SELECT_STATION = ":features:select-station"
    const val SELECT_SEAT = ":features:select-seat"
    const val SELECT_TRIP = ":features:select-trip"
    const val OFFERS = ":features:offers"
    const val ANNOUNCEMENT = ":features:announcement"
    const val INTERNAL_SEARCH = ":features:internal-search"
    const val COMPLETE_USER_INFO = ":features:complete-user-info"



}